//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Knigi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Knigi()
        {
            this.Korzina = new HashSet<Korzina>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_authors { get; set; }
        public string Name { get; set; }
        public Nullable<int> id_ganr { get; set; }
        public string Opisanie { get; set; }
        public Nullable<int> Kol { get; set; }
        public Nullable<int> Price { get; set; }
        public string image { get; set; }
        public Nullable<int> Skidka { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Ganr Ganr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Korzina> Korzina { get; set; }
    }
}
