//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korzina
    {
        public int id { get; set; }
        public Nullable<int> id_kniga { get; set; }
        public Nullable<int> Kol { get; set; }
    
        public virtual Knigi Knigi { get; set; }
    }
}
