//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKZ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PTestKEntities : DbContext
    {
        private static PTestKEntities pTestK;
        public PTestKEntities()
            : base("name=PTestKEntities")
        {
        }

        public static PTestKEntities GetContext()
        {
            if (pTestK == null) pTestK = new PTestKEntities();
            return pTestK;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<Ganr> Ganr { get; set; }
        public virtual DbSet<Knigi> Knigi { get; set; }
        public virtual DbSet<Korzina> Korzina { get; set; }
        public virtual DbSet<Punkt> Punkt { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Zakaz> Zakaz { get; set; }
    }
}
